spring:
  application:
    name: s3_test
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2 # Asia Pacific (Seoul)

  datasource:
    url: jdbc:mysql://localhost:3306/S3-test
    username: root
    password: seoght3658
    driver-class-name: com.mysql.cj.jdbc.Driver

s3:
  bucket-name: bucket-pra
  path: images

  # 업로드 시 이미지 사이즈 제한
#spring:
#  servlet:
#    multipart:
#      max-file-size: 10MB # 최대 파일 사이즈
#      max-request-size: 10MB # 최대 요청 사이즈